version: "3.9"
services:
  mosquitto:
    image: eclipse-mosquitto:2
    volumes:
      - ./config/:/mosquitto/config/
      - ./log/:/mosquitto/log/
      - data:/mosquitto/data/
    ports:
      - 1883:1883
      - 9001:9001

  mqtt-test-publisher:
    image: mqtt-test-publisher:latest
volumes:
  data: ~

  