#Deriving the latest base image
FROM python:latest

# Any working directory can be chosen as per choice like '/' or '/home' etc
# i have chosen /usr/app/src
WORKDIR /usr/app/src

#to COPY the remote file at working directory in container
COPY requirements.txt ./
RUN pip install -r requirements.txt
COPY telemetry-example.log ./messages.log

ARG something
COPY mqtt-test-publisher.py ./

#CMD instruction should be used to run the software
#contained by your image, along with any arguments.

CMD [ "python", "./mqtt-test-publisher.py", "mosquitto:1883", "test", "messages.log"]